### ISSUE TITLE
Problema nel trovare i numeri

### ISSUE THREAD

**Issue by TrueBr** [LukeSavefrogs/inelenco-plus#5]
Stavo provando a cercare i numeri di telefono dei civici dal 16 al 26 di Via Libero Leonardi e come risultato mi è uscito: "Nessun dato trovato". Così ho fatto la verifica su inelenco e al civico 18 è uscito qualche numero di telefono.

![IMG_20211222_103818_464](https://user-images.githubusercontent.com/96523013/147073344-234494a5-36b3-4122-b330-49fe22ae6712.jpg)

![IMG_20211222_103823_701](https://user-images.githubusercontent.com/96523013/147073346-d51ee000-b1c8-4292-a131-c58fe68d7b18.jpg)

**Comment by LukeSavefrogs** [comment]
Analizzando i log risulta essere stato inviato al server un parametro GET `AND%20indirizzo%3A%20` in più... 
Sembra che quindi sia stato inviato un indirizzo vuoto.
```
https://www.inelenco.com/?dir=cerca&cerca=indirizzo%3AVia%20AND%20indirizzo%3ALibero%20AND%20indirizzo%3ALeonardi%20AND%20indirizzo%3A%20AND%20cap%3A%2200173%22%20AND%20tipo%3A%22privato%22%20AND%20indirizzo%3A(indirizzo%3A%22*%2C%2016%22%20OR%20indirizzo%3A%22*%2C%2018%22%20OR%20indirizzo%3A%22*%2C%2020%22%20OR%20indirizzo%3A%22*%2C%2022%22%20OR%20indirizzo%3A%22*%2C%2024%22%20OR%20indirizzo%3A%22*%2C%2026%22)
https://www.inelenco.com/?dir=cerca&cerca=indirizzo%3AVia%20AND%20indirizzo%3ALibero%20AND%20indirizzo%3ALeonardi%20AND%20cap%3A%2200173%22%20AND%20tipo%3A%22privato%22%20AND%20indirizzo%3A(indirizzo%3A%22*%2C%2016%22%20OR%20indirizzo%3A%22*%2C%2018%22%20OR%20indirizzo%3A%22*%2C%2020%22%20OR%20indirizzo%3A%22*%2C%2022%22%20OR%20indirizzo%3A%22*%2C%2024%22%20OR%20indirizzo%3A%22*%2C%2026%22)
```
Sono riuscito a replicare il problema mettendo nell'indirizzo uno spazio finale
![image](https://user-images.githubusercontent.com/33452387/147079141-4100e046-0c5d-4ae5-b0d4-ada955f11d72.png)

**Comment by LukeSavefrogs** [comment]
Sembra essere dovuto quindi all'ultimo aggiornamento che ho fatto per implementare il tipo di corrispondenza Parziale, il quale cerca ogni parola separatamente dividendo la frase ad ogni spazio. Evidentemente viene calcolato come parola anche lo spazio in più.
Cercherò di approfondire...

Grazie della segnalazione 😄 👍🏻

**Comment by LukeSavefrogs** [comment]
Bug fixao qualche tempo fa... Mi ero scordato di segnalarlo 😀

**Comment by LukeSavefrogs** [comment]
## ✔ Bug Fixed ✔
Bug riuscito nel Back-End nel caso fosse presente uno spazio all'inizio della stringa da cercare e risolto con la commit [#466bf114ae5471aeaed06b714e35849e67d94665](https://github.com/LukeSavefrogs/inelenco-unofficial-api/commit/466bf114ae5471aeaed06b714e35849e67d94665)
